### PR TITLE
Dibyasree haiku

### PR DESCRIPTION
**Pull request by dibyasree02**
- Added details

### CODE REVIEW

**Comment by dibyasree02** [comment]
@ltagliaferri please check this.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for your interest in this repository. We would like contributors to provide an original haiku. Please refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more.

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by dibyasree02** [comment]
Fixed it. 

Please have a look. @ltagliaferri

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request, but it does not follow the [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) that are outlined in this repo, so we are closing this PR. If you would like to contribute in the future, please review these guidelines before opening a new pull request. 

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid.*

**Pull request closed without merging**
