### PR TITLE
add progress haiku

### PR DESCRIPTION
**Pull request by sushantkrgeek**

### CODE REVIEW

**Comment by sushantkrgeek** [comment]
Added progress haiku

**Comment by beardicus** [comment]
Thanks for your contribution! This doesn't conform to the standard 5/7/5 syllable format of a haiku. Please check the README file for more formatting information.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Please also only submit the `progress.md` file and remove the second file from this PR. Once you amend this pull request, we can merge it in.

**Comment by sushantkrgeek** [comment]
Thank you for reviewing it. I have made necessary changes and got to learn many things as a beginner.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The haiku looks great, can you remove the second file from this pull request, though? Please just commit `progress.md`

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
