### PR TITLE
Added a haiku to the list of haikus.

### PR DESCRIPTION
**Pull request by gubbnah**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for your interest in this repo, we're only accepting one haiku per contributor. Once you choose one haiku to submit, there are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Comment by gubbnah** [comment]
Hi there, I'm going to stick with the initial commit/pull (_free is free_.)

I deleted the fire_haiku - not sure if I was supposed to do that (oops.)

Look forward to your response in regards to getting this in ship shape.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for updating this pull request, can you please also remove the .gitignore file from your commit? You should only be submitting one markdown file. Thank you!

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
