### PR TITLE
Sorting in C .md

### PR DESCRIPTION
**Pull request by SuryanshSinha2612**
please merge my pull request🙇‍♂️

### CODE REVIEW

**Comment by SuryanshSinha2612** [comment]
please merge my pull request🙇‍♂️🙇‍♂️🙇‍♂️

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by SuryanshSinha2612** [comment]
done changes which would match the [contributing guidelines] . Please see to it 😊

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request, but it does not follow the [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) that are outlined in this repo, so we are closing this PR. If you would like to contribute in the future, please review these guidelines before opening a new pull request. 

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid.*

**Pull request closed without merging**
