### PR TITLE
Add new Haiku

### PR DESCRIPTION
**Pull request by yingyangtongxue**
- The haiku was written by Natsume Soseki

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. We also would like an original haiku from the contributor. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Review by yingyangtongxue — COMMENTED** [review]
- add new haiku written by me

**Comment by yingyangtongxue** [comment]
- add new haiku written by me

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for updating this! As the test is indicating, the second line does not have enough syllables (6 instead of 7), you can update it with something like this:

```
Transform your ideas in code<br>
```
Then it will pass the test and be a valid haiku! Once you add another syllable to the second line, we can merge this in. Thanks!

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
