### PR TITLE
Added asvr haiku

### PR DESCRIPTION
**Pull request by shreya-v7**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by shreya-v7** [comment]
> Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.
> 
> _Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers._

> I have reviewed and made the changes accordingly

**Comment by shreya-v7** [comment]
> _No description provided._

> I have reviewed the guidelines and made the changes

**Comment by shreya-v7** [comment]
Closed

**Pull request closed without merging**
