### PR TITLE
Added rudy, a anonymous

### PR DESCRIPTION
**Pull request by rudyredhat**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for your interest in this repo, we're only accepting one haiku per contributor.

**Comment by rudyredhat** [comment]
Removed one extra haiku.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for removing the extra haiku — there are some changes that need to be made in order to format the haiku correctly.

The first line looks great, the second and third lines need amendments to fit the following syllable format:

```
5 syllables
7 syllables
5 syllables
```
 
Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Comment by rudyredhat** [comment]
Modified as per the contributing guidelines , and as per the 5,7,5 syllables format.

**Comment by ltagliaferri** [comment]
Awesome, thanks for sticking with it and for contributing to open source!

**Pull request merged**
