### PR TITLE
add Sampath Narayanan's hiaku

### PR DESCRIPTION
**Pull request by narayanansampath**
adding my poem for hacktoberfest meetup!

### CODE REVIEW

**Review by narayanansampath — COMMENTED** [review]
Updated cow_haiku.md

**Review by narayanansampath — COMMENTED** [review]
Fixed haiku error as per travis CI

**Review by narayanansampath — COMMENTED** [review]
Fix haiku error

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
