### PR TITLE
Add Bird haiku

### PR DESCRIPTION
**Pull request by connorocampo**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. The second line needs one more syllable, you can try:

```
Hold itself if you can see<br>
```


Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Review by connorocampo — COMMENTED** [review]
Added changes!

**Review by ltagliaferri — APPROVED** [review]
Awesome, looks good!

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
