### PR TITLE
beginner commit - first contribution

### PR DESCRIPTION
**Pull request by MayankMaheshwar**

### CODE REVIEW

**Comment by MayankMaheshwar** [comment]
> _No description provided._
Writing my first contribution in order to do hacktoberfest.thanks

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Comment by MayankMaheshwar** [comment]
Hii. I made the necessary changes please check and let me know for further process

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for updating this, it still is not following the 5-7-5 syllable rule, but something like this would work:

```
Thank you cloud_haiku<br>
For helping me contribute<br>
my first pull request<br>
```

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
