### PR TITLE
Added a new haiku by Rokador

### PR DESCRIPTION
**Pull request by Rokador**
Sometimes you just feel this way when nobody gets you.

### CODE REVIEW

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Comment by ltagliaferri** [comment]
I closed this by mistake, sorry

**Comment by ltagliaferri** [comment]
Could you put this repository back in your GitHub repo list so I can reopen and merge this? Thank you @Rokador

**Comment by Rokador** [comment]
Hi! I resent a pull request like you asked. Thanks for letting me contribute! Have a nice day!

**Pull request closed without merging**
