### PR TITLE
Summer Memories by h3athen

### PR DESCRIPTION
**Pull request by h3athen**
looking forward to it

### CODE REVIEW

**Comment by h3athen** [comment]
can you please specify what I should change

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! Can you add line breaks at the end of each line, as detailed in the [line breaks section of the contributing guidelines](https://github.com/do-community/cloud_haiku#line-breaks). Your haiku lines will look like so:

```
My first haiku line<br>
```

Once you update, we can merge this in, thanks!

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by h3athen** [comment]
Done. Thank you once again <#

**Review by ltagliaferri — APPROVED** [review]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
