### PR TITLE
hactober202

### PR DESCRIPTION
**Pull request by bhagyalakshmiganipisetty**
this is my pull request waiting to be merged..

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! It looks like the file path isn't quite right — can you ensure that it is in the `_haikus/` directory? Once you update the path we can merge this in.

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by bhagyalakshmiganipisetty** [comment]
Thanks for the information
I'm not understanding the situation what's going on and plz let me know how
to insert in _haikus/ directory.
Plz Help me to get out of this situation .

**Comment by ltagliaferri** [comment]
@bhagyalakshmiganipisetty — in your local clone you can move the markdown file to the `_haikus` directory and then push the change to this pull request

**Comment by bhagyalakshmiganipisetty** [comment]
Thanks for your help, I have copied my file to _haikus/directory plz check
it once again.
I'm waiting for your merge request.

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
