### PR TITLE
added note haiku

### PR DESCRIPTION
**Pull request by jayakrishna123**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. Specifically, the last line has too many syllables, you can remove "rewards" and it will pass our test:

```
Be happy and earn<br>
```


Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Comment by jayakrishna123** [comment]
i want to steps to solve this errror, i can't see my repo in haikus

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for your interest in this repository. We would like contributors to provide an original haiku. Please refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more.

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
