### PR TITLE
Added ocean_poem haiku

### PR DESCRIPTION
**Pull request by Saharsh0602**
Added ocean_poem haiku

### CODE REVIEW

**Comment by beardicus** [comment]
i think if you delete `butterfly_poem.md` this PR will pass the tests and be mergeable. that haiku has the wrong number of syllables on multiple lines. `ocean_poem` looks good though.

**Comment by Saharsh0602** [comment]
Sure, I will

**Comment by Saharsh0602** [comment]
Done; I have deleted butterfly_poem.md

**Comment by beardicus** [comment]
Looks great, thanks!

**Pull request merged**
