### PR TITLE
added pull request

### PR DESCRIPTION
**Pull request by SHARMA-SAURAV**
added my first pull request

### CODE REVIEW

**Comment by SHARMA-SAURAV** [comment]
Greeting cloud haiku,
Please adding the "hacktoberfest-accepted" label to the PR.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Specifically, remove the two non-`.md` files from this PR. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by SHARMA-SAURAV** [comment]
added chances please do check

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for updating this — can you remove the `.suo` and `.sqlite` files from this pull request? You may want to close this pull request and reopen it with just `pull2.md` being committed. Thank you!

**Comment by SHARMA-SAURAV** [comment]
I had closed and reopen it. Please check  if it is done if not please tell how to remove them (.suo , .sqlite)

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The `.suo` and `.sqlite` files are still in here. When you close and then reopen this pull request, make sure only `pull2.md` is the file being committed. Thank you!

**Pull request closed without merging**
