### PR TITLE
added corona_effect haiku

### PR DESCRIPTION
**Pull request by Utkarsh299-tech**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Please do not override the test as a contributor. Remove the testing line so that our test suite can run. Refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more about our test suite and why we are using it.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by Utkarsh299-tech** [comment]
> Please do not override the test as a contributor. Remove the testing line so that our test suite can run. Refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more about our test suite and why we are using it.
> 
> _Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers._

Fixed testing.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Hi — you need to remove the line that says `test: false` because our test suite needs to run. The submitted poem is not a valid haiku, so it needs to be tested and modified based on the test output.

**Comment by Utkarsh299-tech** [comment]
> Hi — you need to remove the line that says `test: false` because our test suite needs to run. The submitted poem is not a valid haiku, so it needs to be tested and modified based on the test output.

Hello, I did the change as you said.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for disabling the test override. The test output indicates that this is not passing the test. This should be a 3-line poem, can you remove the final line? Otherwise it looks good to me and we can merge once this is updated.

**Comment by Utkarsh299-tech** [comment]
> Thanks for disabling the test override. The test output indicates that this is not passing the test. This should be a 3-line poem, can you remove the final line? Otherwise it looks good to me and we can merge once this is updated.

Hi, I removed the last line.

**Review by ltagliaferri — APPROVED** [review]

**Comment by ltagliaferri** [comment]
Thank you for this haiku, sticking with it and updating it, and for contributing to open source 🎉

**Comment by Utkarsh299-tech** [comment]
> Thank you for this haiku, sticking with it and updating it, and for contributing to open source 🎉

Thank you for accepting my PR.
I'm very glad that my PR got merged.😊

**Pull request merged**
