### PR TITLE
Ankit Jaipuriar haiku

### PR DESCRIPTION
**Pull request by Ankit-Jaipuriar**
Thanks for reading!
Please accept it under Hacktoberfest.

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Can you remove the empty file?

**Comment by Ankit-Jaipuriar** [comment]
> Can you remove the empty file?

Yes sir, I have deleted it now.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Instead of deleting `fur.md` can you remove it from the pull request?

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request. 

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Pull request closed without merging**
