### PR TITLE
Added potato haiku

### PR DESCRIPTION
**Pull request by akshat-max**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Comment by akshat-max** [comment]
I have changed, please verify.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The last line still needs more syllables, you can try:

```
I really love tech!<br>
```

Thanks!

**Comment by akshat-max** [comment]
done the changes 😃

Thank you for the help!

**Comment by ltagliaferri** [comment]
Thanks for updating this and for being a part of open source!

**Pull request merged**
