### PR TITLE
I am Hacker, Dont Open this Flag

### PR DESCRIPTION
**Pull request by fsociety343**
Hay there...

This is a my first contribution on Pull Request

Thanks.

### CODE REVIEW

**Comment by beardicus** [comment]
looks good but each line needs to end with a `<br>` tag in order to render properly. please update and push the changes to this PR. thanks!

**Comment by fsociety343** [comment]
> 
> 
> looks good but each line needs to end with a `<br>` tag in order to render properly. please update and push the changes to this PR. thanks!

ohh okay sir, thanks for review :)

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Hi there — the third line has 8 syllables when it should have 5.

The second line also reads as 6 instead of 7, but not sure how you are counting it.

**Review by ltagliaferri — APPROVED** [review]
I revised a little bit to get it to fit the form, thank you for sticking with this!

**Pull request merged**
