### PR TITLE
Create isabelle_haikus.md - test for women who code

### PR DESCRIPTION
**Pull request by isabelle-dr**

### CODE REVIEW

**Comment by isabelle-dr** [comment]
no need to merge this :)

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks, Isabelle, for joining the session today and for opening this pull request! If you would like to update this, here is the guidance you may want about the haiku, from the [Readme](https://github.com/do-community/cloud_haiku#haiku-format) file. This repo was inspired by one of the co-founders of Hacktoberfest who is a haiku poet 😄

**Comment by isabelle-dr** [comment]
I updated it to have a real haiku :) thanks for today's session!

**Review by ltagliaferri — APPROVED** [review]

**Comment by ltagliaferri** [comment]
Awesome haiku! Thanks for submitting this pull request, for attending the session, and for being a part of open source 🎉

**Pull request merged**
