### PR TITLE
Added kumar haiku

### PR DESCRIPTION
**Pull request by Kumar-gaurav07**
Basically this is for demo purpose to learn about the Pull request , hopefully, everything went right

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
This needs to follow a line format of 
5 syllables
7 syllables
5 syllables

For the first line, you can change it to:

```
Before software can<br>
```

And then that will be 5 syllables. Once you change that line to 5 syllables, the second line to 7 syllables, and the third line to 5 syllables we can merge this pull request in.

**Review by Kumar-gaurav07 — COMMENTED** [review]
Based on your requirement it is in 5,7,5

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The second and third line now have too many syllables, and there should only be three lines total.

**Review by Kumar-gaurav07 — COMMENTED** [review]
Hope this will satisfy the requirement. if not please let me know I'll try again

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
We are almost there, the second line is too short now, you can try:

```
When you do really have to<br>
```

**Review by ltagliaferri — APPROVED** [review]
Yes! Looks great, thank you for sticking with us!

**Pull request merged**
