### PR TITLE
Added Dockerfile for this application

### PR DESCRIPTION
**Pull request by KemilaTharaka**
Please review my dockerfile!

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by KemilaTharaka** [comment]
> Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.
> 
> _Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers._

Sure I'll do the changes required. Could you pls mention your suggestions?

**Comment by ltagliaferri** [comment]
Please read the linked contributing guidelines in order to format a valid pull request, thanks!

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
