### PR TITLE
Gandem vijay kumar haiku

### PR DESCRIPTION
**Pull request by GandemVijaykumar**
thanks for reading my pull request!!

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for your interest in this repo, we're only accepting one haiku per contributor, please remove one of the files.

**Comment by GandemVijaykumar** [comment]
Sir/mam thank you for the valuable review!!
I have removed one of file.

**Comment by GandemVijaykumar** [comment]
Sir/mam Thank you for your valuable review.
I removed one of the file.

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
