### PR TITLE
feat: add sherman's haiku

### PR DESCRIPTION
**Pull request by shermanhui**
adding my poem for my hacktoberfest meet up demo!

### CODE REVIEW

**Comment by alexcheuk** [comment]
This is a decent haiku. The Feels.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! It looks like the file path isn't quite right — can you ensure that it is only in the `_haikus/` directory? Once you update the path we can merge this in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by shermanhui** [comment]
@ltagliaferri Thanks for that! I've updated it to be in the right repository

**Review by ltagliaferri — APPROVED** [review]
Great, thank you for updating this!

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Comment by shermanhui** [comment]
Thanks for managing this repository @ltagliaferri, I really appreciate the work put in! This repo was a great help to teach the participants all about making their first contribution to open source during the Hacktoberfest meetup I hosted! 🎉

**Pull request merged**
