### PR TITLE
Added time haiku

### PR DESCRIPTION
**Pull request by yulidarmaulana**
thank you for creating this repository for those of us who are just starting to learn kontribusi on open source.

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made to the syllable count in order to have a valid haiku.

A haiku is composed of 3 lines. The first line is 5 syllables long, the second line is 7 syllables long, and the third line is 5 syllables long. Although the majority of the haikus here are written in English, you can submit a haiku in any human language.

Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by yulidarmaulana** [comment]
Hello. Thanks for your comment. sorry for my inaccuracy about the guild line. i am trying to understand about the three line format and it has a total of 17 syllables. and 5-7-5 syllable format poems in three lines.

I hope you can understand about my problem

**Review by yulidarmaulana — COMMENTED** [review]
Hello, I hope this is correct! according to the established guideline. thank you.

**Review by ltagliaferri — APPROVED** [review]
Thanks for sticking with this and for contributing to open source 🎉

**Comment by yulidarmaulana** [comment]
you're welcome :100:

**Pull request merged**
