### PR TITLE
Added a new Haiku (:-)

### PR DESCRIPTION
**Pull request by Zinkuth**
Added a new haiku, can be found in relationships.md

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
It looks like you deleted this file, can you please add it back in so we can consider it for the repository? Thank you!

**Comment by Zinkuth** [comment]
I have added again the file. Thanks!

**Comment by ltagliaferri** [comment]
Awesome, thank you for updating this! Merging your haiku in now 🎉

**Review by ltagliaferri — COMMENTED** [review]
Looks great, thank you for updating!

**Pull request merged**
