### PR TITLE
Added Whale haiku

### PR DESCRIPTION
**Pull request by Srikark-17**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please submit an original haiku, and do not edit others' files. Consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Comment by Srikark-17** [comment]
Thank you for letting me know on what I should improve on! I have made amendments to this pull request by adding a different haiku. Please let me know if this is applicable.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for updating this! Can you remove the `python-syntax.md` file from your pull request? You can unstage both and just commit the `winter.md` one. This way we don't edit someone else's haiku.

Thank you!

**Comment by Srikark-17** [comment]
I have deleted that file. Can you merge it now

**Comment by ltagliaferri** [comment]
Hi @Srikark-17 — the file needs to be removed from the pull request, not deleted. Deleting the file from your pull request will remove it from the repo. Instead, you need to remove it from the commit (so that you are only committing the `winter.md` file. Thank you!

**Comment by Srikark-17** [comment]
Hi! I am going to make a new pull request instead

**Pull request closed without merging**
