### PR TITLE
Adding my new haiku Inner Wolf

### PR DESCRIPTION
**Pull request by athosrsilva**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! It looks like the file path isn't quite right — can you ensure that it is in the `_haikus/` directory? Once you update the path we can merge this in.

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by athosrsilva** [comment]
> Thank you for submitting this haiku! It looks like the file path isn't quite right — can you ensure that it is in the `_haikus/` directory? Once you update the path we can merge this in.
> 
> _Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers._

Hello, the file was moved to "_haikus/" as required!

**Comment by athosrsilva** [comment]
> Thank you for submitting this haiku! It looks like the file path isn't quite right — can you ensure that it is in the `_haikus/` directory? Once you update the path we can merge this in.
> 
> _Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers._

@ltagliaferri

**Review by ltagliaferri — APPROVED** [review]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
