### PR TITLE
deleted test dot js and added Cloudy miner

### PR DESCRIPTION
**Pull request by CounsellorDev**
Guess, this would be approved

### CODE REVIEW

**Comment by beardicus** [comment]
This haiku looks good and would probably pass the tests, but you've deleted the test script so the tests aren't running. This PR cannot be merged w/ the deletion. You can read this stackoverflow thread to learn how to reverse your commit and "undelete" the `test.js` script:

https://stackoverflow.com/questions/12481639/remove-files-from-git-commit

But that's pretty complex. You could also just start over and try a new PR where you only check in your haiku file.

Thanks!

**Comment by beardicus** [comment]
If you want to fix this PR, instead of opening a new one, push your changes and comment here and we'll happily re-open and merge.

**Comment by CounsellorDev** [comment]
what is happening?? But that was the task, you assigned me to do.

**Comment by beardicus** [comment]
yeah, i think we've had some miscommunication here. let me try to fix your PR... give me a bit.

**Comment by beardicus** [comment]
ok, fixed. thanks!

**Pull request merged**
