### PR TITLE
Jasonj

### PR DESCRIPTION
**Pull request by JasonJia12**
Jason's haiku

### CODE REVIEW

**Comment by JasonJia12** [comment]
Thanks

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! Please remove the `jason12.md` haiku as we are only accepting one *original* haiku per contributor.

You can consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by JasonJia12** [comment]
I deleted jason12.md

**Review by ltagliaferri — APPROVED** [review]

**Comment by ltagliaferri** [comment]
Awesome, thank you for updating this and for being a part of open source 🎉

**Pull request merged**
