### PR TITLE
anis jradah haiku

### PR DESCRIPTION
**Pull request by anisj**
Thank you for taking the time to read my pull request!

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for your interest in this repository. We would like contributors to provide an original haiku. Please refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more.

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid. Also note that after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by anisj** [comment]
Text was adjusted as requested. (following the guidelines)

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request, but it does not follow the [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) that are outlined in this repo (of submitting an original haiku), so we are closing this PR. If you would like to contribute in the future, please review these guidelines before opening a new pull request. 

*Please note: maintainers will only go through one round of review, first reviews that are not sufficiently addressed will be closed and marked invalid.*

**Comment by anisj** [comment]
It was a pleasure to participate. 
Also,  can you please let me know what needs to be altered in this PR as I'm unsure? I used a syllable counter to count the syllable.

**Pull request closed without merging**
