### PR TITLE
Added I am a Nerd

### PR DESCRIPTION
**Pull request by pheiduck**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Review by pheiduck — COMMENTED** [review]
5-7-5 format now correct so it can be merged to master @ltagliaferri

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for updating this! It looks really good, but I am reading `IRC` as `I` - `R` - `C` — is that how you intend it?

If so, I would do something like:

```
It's in IRC <br>
```

Thanks!

**Comment by ltagliaferri** [comment]
> Thanks for updating this! It looks really good, but I am reading `IRC` as `I` - `R` - `C` — is that how you intend it?
> 
> If so, I would do something like:
> 
> ```
> It's in IRC <br>
> ```
> 
> Thanks!

Note that the testing may fail with this, but we can override the test.

**Review by ltagliaferri — APPROVED** [review]

**Comment by ltagliaferri** [comment]
Thank you so much for sticking with this and revising! The haiku looks great and we are merging it in now 🎉

**Pull request merged**
