### PR TITLE
Added a new file for haiku poems - Contribution to Hacktoberfest 2020

### PR DESCRIPTION
**Pull request by vifeng**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Comment by vifeng** [comment]
Hi, I can't see why my pull request needs work. Could you please help me ? Thanks, virginie

**Comment by ltagliaferri** [comment]
It looks good now, thank you!

**Comment by vifeng** [comment]
thanks for your review :)

**Pull request merged**
