### PR TITLE
Old Pond.md

### PR DESCRIPTION
**Pull request by Sandeep228**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thanks for your interest in this repository. We would like contributors to provide an original haiku. Please refer to our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) to learn more.

**Comment by Sandeep228** [comment]
@ltagliaferri  Done

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for updating, the syllables are not quite right, should be following 5-7-5 format

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
