### PR TITLE
Added haiku 

### PR DESCRIPTION
**Pull request by cnfranco**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The formatting and syllables are a little off, here's my suggestion:

```
---
layout: haiku
title: Galactic Enigma
author: Camila Franco
---

In vast galaxies<br>
Find infinite mysteries<br>
Cosmic tapestries<br>
```

**Comment by cnfranco** [comment]
Changes done.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
It's looking the same to me with the formatting not right and too many syllables

**Comment by cnfranco** [comment]
The suggested syllable counter isn't working today (for me, at least), but I found another one that has the same function. According to it, the syllable division is correct now.
Could you check again please?

haiku

**Comment by ltagliaferri** [comment]
> The suggested syllable counter isn't working today (for me, at least), but I found another one that has the same function. According to it, the syllable division is correct now. Could you check again please?
> 
> haiku

It's not the syllables, it's the format of the top matter

**Comment by cnfranco** [comment]
> > The suggested syllable counter isn't working today (for me, at least), but I found another one that has the same function. According to it, the syllable division is correct now. Could you check again please?
> > haiku
> 
> It's not the syllables, it's the format of the top matter

I fixed this now.

**Review by ltagliaferri — APPROVED** [review]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
