### PR TITLE
Vinishbhaskar patch 1

### PR DESCRIPTION
**Pull request by Vinishbhaskar**
created two haiku
grwon.md
goose.md

Please check it

### CODE REVIEW

**Comment by Vinishbhaskar** [comment]
please accept it as "hacktoberfest-accepted"

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for your interest in this repo, we're only accepting one haiku per contributor, please choose one and then we can iterate and merge. Thanks!

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you, looks good!

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
