### PR TITLE
Added Pork Bellly Haiku

### PR DESCRIPTION
**Pull request by toanhtran**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! The second line has a few too many syllables. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
I'm counting 10 syllables instead of 7 in the second line. Isn't BBQ three syllables (B-B-Q)? Maybe you can try:

```
Cooked, roasted, deep-fried, stewed oh<br>
```
and leave out the BBQ part? Thanks!

**Comment by toanhtran** [comment]
Third time is a charm hopefully. I corrected the 2nd line of the pork belly haiku.

**Comment by ltagliaferri** [comment]
Awesome, thanks for updating and for contributing to open source!

**Pull request merged**
