### PR TITLE
Added a new haiku in Binural_Beats.md file

### PR DESCRIPTION
**Pull request by LoSTOPerativE**
Hello, I hope this suffices! I am excited for Hacktoberfest and cannot wait to contribute more. :)

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for your interest in Cloud Haiku! Please submit one new, original haiku in markdown format in order to contribute. Edits on existing haikus do not count as a contribution. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) for more guidance on how to create a valid pull request.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by LoSTOPerativE** [comment]
Hello. Thank your for your comment. Did the haiku I submitted not comply with the guildlines? I'm a little confused.

**Comment by ltagliaferri** [comment]
> Hello. Thank your for your comment. Did the haiku I submitted not comply with the guildlines? I'm a little confused.

Please review the contributing guidelines again. It needs to be a markdown file, it needs to have a title, and you should not have other files in your pull request.

**Comment by LoSTOPerativE** [comment]
Thank you for the information, I will correct the mistakes.

**Pull request closed without merging**
