### PR TITLE
added pull

### PR DESCRIPTION
**Pull request by SrivastavaSatyam**
my first work on open source. Tried to pull request

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The first line is one syllable over, maybe it can be:

```
Learning new things is <br>
```

Once you update this we can merge it in 😄

**Review by SrivastavaSatyam — COMMENTED** [review]
changed content

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The first line now has 6 syllables, it should have 5 syllables. Please update.

**Comment by ltagliaferri** [comment]
Excellent, thanks for updating!

**Pull request merged**
