### PR TITLE
Added haiku on nature

### PR DESCRIPTION
**Pull request by amoghrajesh**

### CODE REVIEW

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for your interest in Cloud Haiku! Please submit one new, original haiku in markdown format in order to contribute. Edits on existing haikus do not count as a contribution. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) for more guidance on how to create a valid pull request.

**Comment by amoghrajesh** [comment]
Hey @ltagliaferri doing that change ie. making line 1 as "SARS Covid19" would break the haiku structure of 5 7 5

**Review by amoghrajesh — COMMENTED** [review]
I am unable to delete this file for some reason

**Comment by ltagliaferri** [comment]
You'll have to unstage the file. There are some guides about it, see, for example: https://devconnected.com/how-to-unstage-files-on-git/

**Comment by amoghrajesh** [comment]
Closing it because the structure got too complex on my system, will make another PR with only new file @ltagliaferri

**Pull request closed without merging**
