### PR TITLE
Added a haiku on achieving goals

### PR DESCRIPTION
**Pull request by mukhtar-github**
Participating in Hacktoberfest

### CODE REVIEW

**Comment by mukhtar-github** [comment]
Participating in Hacktoberfest

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
This looks ok, you need to remove the extra parts like the three backtics (```) throughout and the `yaml`.

**Comment by mukhtar-github** [comment]
Changes for correction made as required

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
