### PR TITLE
Added Shreya haiku

### PR DESCRIPTION
**Pull request by shreya-v7**

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! There are some changes that need to be made to the syllable count in order to have a valid haiku.

A haiku is composed of 3 lines. The first line is 5 syllables long, the second line is 7 syllables long, and the third line is 5 syllables long. Although the majority of the haikus here are written in English, you can submit a haiku in any human language.

Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after more than two days of inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by shreya-v7** [comment]
Changes done

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Try a syllable counter such as [https://syllablecounter.net/](https://syllablecounter.net/). This is still not following the format.

**Comment by shreya-v7** [comment]
Updated accordingly

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The last line needs one more syllable, could be `in harmony tunes` or `the harmony tunes` for example.

**Comment by shreya-v7** [comment]
Updated last line, changes performed

**Review by ltagliaferri — APPROVED** [review]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
