### PR TITLE
hactoberfest2022

### PR DESCRIPTION
**Pull request by raj-hero**
Do add the hactoberfest-accepted tag if no issues are found. Mention if any issues are found for rectification

### CODE REVIEW

**Comment by raj-hero** [comment]
> Do add the hactoberfest-accepted tag if no issues are found. Mention if any issues are found for rectification

@ltagliaferri

**Comment by raj-hero** [comment]
@ltagliaferri Do add the hactoberfest-accepted tag if no issues are found. Mention if any issues are found to be solved

**Comment by raj-hero** [comment]
> @ltagliaferri Do add the hactoberfest-accepted tag if no issues are found. Mention if any issues are found to be solved

@ltagliaferri

**Comment by raj-hero** [comment]
@ltagliaferri  Do add the hactoberfest-accepted tag if no issues are found. Mention if any issues are found so that I can rectify them

**Review by ltagliaferri — APPROVED** [review]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
