### PR TITLE
Added a new haiku

### PR DESCRIPTION
**Pull request by AgaskarJ**
Added a sample Haiku by Yosa Buson

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this haiku! Can you add line breaks at the end of each line, as detailed in the [line breaks section of the contributing guidelines](https://github.com/do-community/cloud_haiku#line-breaks). Your haiku lines will look like so:

```
My first haiku line<br>
```

Once you update, we can merge this in, thanks!

**Comment by AgaskarJ** [comment]
@ltagliaferri Thank you for your feedback! Added line breaks and a new haiku in the correct folder

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for adding the line breaks. The last line is still too long, and please make sure you are submitting an original haiku, not one written by Basho. Thanks!

**Comment by ltagliaferri** [comment]
Thank you for opening this pull request. The changes requested have not been addressed over the course of a few days, so we are closing this PR due to inactivity and are marking it as `invalid`. If you would like to try again, please open a new pull request.

**Pull request closed without merging**
