### PR TITLE
added Files Fly Haiku

### PR DESCRIPTION
**Pull request by Catzla**
I added a haiku about the cloud for Hacktoberfest 2021

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.

*Please note: after inactivity, pull requests are subject to being closed and marked invalid by maintainers.*

**Comment by Catzla** [comment]
Changed and all set on fitting the format and topic now 

> Thank you for submitting this pull request! There are some changes that need to be made in order to format this correctly. Please consult our [contributing guidelines](https://github.com/do-community/cloud_haiku#contributing) if you need extra guidance. Once you amend this pull request, we can merge it in.
> 
> _Please note: after inactivity, pull requests are subject to being closed and marked invalid by maintainers._

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
The last line is one syllable too long, you can try

```
Files fly through sky <br>
```

and it would be correct

**Review by ltagliaferri — APPROVED** [review]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
