### PR TITLE
Added README-Italian.md

### PR DESCRIPTION
**Pull request by mRuggi**
I translated the readme file of this repo in my mother language (Italian) and added an example of syllabation in italian

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
This looks really great! Thank you so much for doing this! 

A few items I would be interested in hearing your thoughts on —

1. Under `### Scrivere un Haiku` the line "Il tuo haiku dovrà essere difficile ma divertente da scrivere." — in our English README.md the note about the haiku writing process being "challenging" we meant more in the manner of "stimolante" rather than "difficile". Maybe this is an opportunity for us to revise the English too. What do you think of using a different phrasing to capture this feeling of a challenge without making the haiku writing process seem very difficult? I note this because I would like to invite people to try and not make it seem too difficult. 

2. Would you be open to showing the example haiku in Italian here? You do not need to translate the one here, you can write a different one or use one that is popular and known.

3. I think you can translate `Sammy the Shark` to `Sammy Squalo` (I think I will change the name to `Sammy Shark` in English too, that is the DigitalOcean mascot 😄 )

Let me know what you think. I am also happy to make modifications if you do not have time for it. All the best

**Comment by mRuggi** [comment]
> This looks really great! Thank you so much for doing this!
> 
> A few items I would be interested in hearing your thoughts on —
> 
> 1. Under `### Scrivere un Haiku` the line "Il tuo haiku dovrà essere difficile ma divertente da scrivere." — in our English README.md the note about the haiku writing process being "challenging" we meant more in the manner of "stimolante" rather than "difficile". Maybe this is an opportunity for us to revise the English too. What do you think of using a different phrasing to capture this feeling of a challenge without making the haiku writing process seem very difficult? I note this because I would like to invite people to try and not make it seem too difficult.
> 2. Would you be open to showing the example haiku in Italian here? You do not need to translate the one here, you can write a different one or use one that is popular and known.
> 3. I think you can translate `Sammy the Shark` to `Sammy Squalo` (I think I will change the name to `Sammy Shark` in English too, that is the DigitalOcean mascot smile )
> 
> Let me know what you think. I am also happy to make modifications if you do not have time for it. All the best

Here's my tought about the changes
For point number 1 i think you're right, i'll make the change right now.
For point number 2 i'll try to write an haiku in Italian and update the example.
For point number 3, well, i didn't translate Sammy the Shark in italian knowing that is the DigitalOcean mascot, but if you think this should be done, i'll translate in "Sammy lo Squalo" ,because using the article "lo" as in the original "Sammy the Shark" seems more appropriate.

Let me know if I can proceed, sincerely, mRuggi

**Comment by mRuggi** [comment]
@ltagliaferri done!

**Review by ltagliaferri — APPROVED** [review]
Awesome! Thank you! I was thinking of changing it to "Sammy Shark" because that seems to be the direction the mascot name is going in, but we'll keep the "the" / "lo" in there for now 😄 

Thank you again for this and for updating, Happy Hacktoberfest 🍂

**Pull request merged**
