### PR TITLE
Goofer haiku

### PR DESCRIPTION
**Pull request by GooferG**
I hope I did it correctly. 

Appreciate the feedback!

### CODE REVIEW

**Review by ltagliaferri — CHANGES_REQUESTED** [review]
`2022_GooferHaiku_first.md` looks great, can you remove the other file?

**Comment by GooferG** [comment]
Removed the previous one! Thanks a bunch!  👍🏽

**Comment by GooferG** [comment]
Apologies, I got a bit confused and deleted the wrong file. Now it should be updated correctly.

**Comment by ltagliaferri** [comment]
Thank you for this haiku and for contributing to open source 🎉

**Pull request merged**
